/**
 * @file scripts/seedDemo.js
 * @description
 *   Seeds the demo schema with data mirroring the real dbo structure:
 *   real event types, real Riverdale Arena / OGS Garage locations, real
 *   session / shift layout, full volunteer roster (anonymized emails),
 *   and correct oversight structure.
 *
 *   Safe to re-run — clears all demo tables before inserting.
 *
 * Usage (from project root):
 *   node scripts/seedDemo.js
 *
 * Required env vars:
 *   AZSQLServer / AZURE_SQL_SERVER   - SQL server FQDN
 *   AZSQLDB / AZURE_SQL_DATABASE     - Database name
 *   DEMO_DB_USER                     - parking_demo
 *   DEMO_DB_PASSWORD                 - password set in setupDemoSchema scripts
 *
 * Named login accounts (password: Demo@2026!):
 *   admin@demo.com          ADMIN           (mirrors Jacob Ladd)
 *   asstadmin@demo.com      ASSISTANT_ADMIN (mirrors Danny Munoz)
 *   overseer@demo.com       OVERSEER        (mirrors Ryan Fagan)
 *   keyman@demo.com         KEYMAN          (mirrors Matthew Kyarsgaard)
 *   desk@demo.com           DESK            (mirrors Jason Ladd)
 *   volunteer@demo.com      REGISTERED      (mirrors Winston Austin)
 */

import sql from "mssql";
import crypto from "crypto";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

// ---------------------------------------------------------------------------
// Bootstrap .env for local runs
// ---------------------------------------------------------------------------
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
try {
  const { default: dotenv } = await import("dotenv");
  dotenv.config({ path: join(__dirname, "..", ".env") });
} catch {
  /* env may already be set */
}

function log(...a) {
  console.log(`[${new Date().toISOString()}] [seedDemo]`, ...a);
}
function logError(...a) {
  console.error(`[${new Date().toISOString()}] [seedDemo:ERROR]`, ...a);
}

// ---------------------------------------------------------------------------
// Password hashing (mirrors lib/passwordVer.js)
// ---------------------------------------------------------------------------
function hashPassword(password) {
  const salt = crypto.randomBytes(16);
  const hash = crypto.pbkdf2Sync(password, salt, 100_000, 32, "sha256");
  return { hash, salt, iterations: 100_000, algo: "PBKDF2-SHA256" };
}

// ---------------------------------------------------------------------------
// Connection
// ---------------------------------------------------------------------------
const SQL_SERVER =
  process.env.AZSQLServer ||
  process.env.AZURE_SQL_SERVER ||
  process.env.SQL_SERVER ||
  "";
const SQL_DB =
  process.env.AZSQLDB ||
  process.env.AZURE_SQL_DATABASE ||
  process.env.SQL_DATABASE ||
  "";
const DEMO_USER = process.env.DEMO_DB_USER || "parking_demo";
const DEMO_PASS = process.env.DEMO_DB_PASSWORD || "";

const missing = [
  !SQL_SERVER && "AZSQLServer",
  !SQL_DB && "AZSQLDB",
  !DEMO_PASS && "DEMO_DB_PASSWORD",
].filter(Boolean);
if (missing.length) {
  logError("Missing env vars:", missing.join(", "));
  process.exit(1);
}

const poolConfig = {
  server: SQL_SERVER,
  database: SQL_DB,
  port: 1433,
  authentication: {
    type: "default",
    options: { userName: DEMO_USER, password: DEMO_PASS },
  },
  options: {
    encrypt: true,
    trustServerCertificate: false,
    connectTimeout: 30_000,
    requestTimeout: 30_000,
  },
};

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------
const YEAR = 2026;
const DEMO_PASS_PW = "Demo@2026!";

// Volunteers whose original dbo IDs map to named demo login accounts
const NAMED_EMAIL_MAP = {
  80: "admin@demo.com",
  195: "asstadmin@demo.com",
  81: "overseer@demo.com",
  88: "keyman@demo.com",
  237: "desk@demo.com",
  137: "volunteer@demo.com",
};

// ---------------------------------------------------------------------------
// Source data — mirrors dbo exactly
// ---------------------------------------------------------------------------

const EVENT_TYPES = [
  {
    oldId: 1,
    name: "Ingress",
    description: "Morning shift of incoming cars",
    color: "#6c757d",
  },
  {
    oldId: 2,
    name: "Park Assistance",
    description: "Assist friends with parking in lots/garages",
    color: "#b0dd97",
  },
  {
    oldId: 3,
    name: "Security",
    description: "Garage Security",
    color: "#ffc35c",
  },
  {
    oldId: 4,
    name: "Pickup/Drop-off",
    description: "Assistance in front of building",
    color: "#6e5bfb",
  },
  {
    oldId: 5,
    name: "Parking Meeting",
    description: "Meeting for Parking Department",
    color: "#e23c3c",
  },
  {
    oldId: 6,
    name: "Signs",
    description: "Place, remove, replace signage",
    color: "#318081",
  },
  {
    oldId: 7,
    name: "Mobile Support",
    description: "Assist w/ flats, batteries, lockouts",
    color: "#f0eb4c",
  },
];

const LOCATIONS = [
  {
    oldId: 1,
    name: "Civic Center Garage",
    type: "location",
    description: null,
    capacity: 800,
    address: "129 Civic Plaza Dr, Riverdale, NY 12207",
    lat: 42.647658,
    lng: -73.757479,
    maps_url: "https://maps.app.goo.gl/7CmFTKHE4yFeP8v69",
  },
  {
    oldId: 2,
    name: "Arena Garage",
    type: "location",
    description: "Preferred Handicap and Disabled Garage",
    capacity: 800,
    address: "12 Arena Way",
    lat: null,
    lng: -7.375626,
    maps_url: "https://maps.app.goo.gl/YvA11LwadWDrZCgm7",
  },
  {
    oldId: 3,
    name: "Mobile Support",
    type: "task",
    description: null,
    capacity: null,
    address: null,
    lat: null,
    lng: null,
    maps_url: null,
  },
  {
    oldId: 4,
    name: "Signs",
    type: "task",
    description: null,
    capacity: null,
    address: null,
    lat: null,
    lng: null,
    maps_url: null,
  },
  {
    oldId: 5,
    name: "Arrival & Departure Zone",
    type: "location",
    description: null,
    capacity: null,
    address: "51 12 Arena Way, Riverdale, NY 12207",
    lat: 42.647634,
    lng: -73.754184,
    maps_url: "https://maps.app.goo.gl/WoxUwYneUSYVWcbZ9",
  },
  {
    oldId: 6,
    name: "Shuttle Station",
    type: "location",
    description: "South side of arena, Commerce St entrance",
    capacity: null,
    address: "51 12 Arena Way, Riverdale, NY 12207",
    lat: 42.647892,
    lng: -73.754608,
    maps_url: "https://maps.app.goo.gl/WoxUwYneUSYVWcbZ9",
  },
  {
    oldId: 7,
    name: "Mezzanine - Riverdale Arena",
    type: "location",
    description: "Halfway up escalators on right side, as viewed from main entrance.",
    capacity: null,
    address: "51 12 Arena Way, Riverdale, NY",
    lat: 42.647634,
    lng: -73.754184,
    maps_url: "https://maps.app.goo.gl/WoxUwYneUSYVWcbZ9",
  },
  {
    oldId: 8,
    name: "Millhaven KH of JW",
    type: "location",
    description: null,
    capacity: null,
    address: "500 Riverside Rd, Millhaven, NY 12033",
    lat: 42.504519,
    lng: -73.67427,
    maps_url: "https://maps.app.goo.gl/z8Uj5DCGnEbyQBdG7",
  },
];

const CONVENTION_DAYS = [
  {
    oldId: 23,
    label: "Thursday Test",
    date: "2026-05-21",
    start: "09:20:00",
    end: "15:45:00",
    schedulable: 0,
  },
  {
    oldId: 15,
    label: "Training",
    date: "2026-05-23",
    start: "10:30:00",
    end: "13:30:00",
    schedulable: 0,
  },
  {
    oldId: 1,
    label: "Friday",
    date: "2026-07-03",
    start: "09:20:00",
    end: "16:45:00",
    schedulable: 1,
  },
  {
    oldId: 10,
    label: "Saturday",
    date: "2026-07-04",
    start: "09:20:00",
    end: "04:30:00",
    schedulable: 1,
  },
  {
    oldId: 14,
    label: "Sunday",
    date: "2026-07-05",
    start: "09:20:00",
    end: "15:45:00",
    schedulable: 1,
  },
];

// Sessions keyed by old convention_day_id
const SESSIONS = [
  // Friday (day 1)
  {
    oldId: 7,
    oldDayId: 1,
    label: "Pre-Session",
    order: 1,
    start: "05:30:00",
    end: "09:45:00",
  },
  {
    oldId: 1,
    oldDayId: 1,
    label: "Morning A",
    order: 2,
    start: "09:20:00",
    end: "10:40:00",
  },
  {
    oldId: 2,
    oldDayId: 1,
    label: "Morning B",
    order: 2,
    start: "10:40:00",
    end: "12:15:00",
  },
  {
    oldId: 3,
    oldDayId: 1,
    label: "Lunch",
    order: 3,
    start: "12:15:00",
    end: "13:35:00",
  },
  {
    oldId: 5,
    oldDayId: 1,
    label: "Afternoon A",
    order: 5,
    start: "13:35:00",
    end: "14:50:00",
  },
  {
    oldId: 6,
    oldDayId: 1,
    label: "Afternoon B",
    order: 6,
    start: "14:50:00",
    end: "16:45:00",
  },
  {
    oldId: 8,
    oldDayId: 1,
    label: "Post-Session",
    order: 10,
    start: "16:30:00",
    end: "18:30:00",
  },
  // Saturday (day 10)
  {
    oldId: 23,
    oldDayId: 10,
    label: "Pre-Session",
    order: 1,
    start: "05:30:00",
    end: "09:45:00",
  },
  {
    oldId: 24,
    oldDayId: 10,
    label: "Morning A",
    order: 2,
    start: "09:20:00",
    end: "10:25:00",
  },
  {
    oldId: 25,
    oldDayId: 10,
    label: "Morning B",
    order: 2,
    start: "10:25:00",
    end: "12:10:00",
  },
  {
    oldId: 26,
    oldDayId: 10,
    label: "Lunch",
    order: 3,
    start: "12:10:00",
    end: "13:35:00",
  },
  {
    oldId: 27,
    oldDayId: 10,
    label: "Afternoon A",
    order: 5,
    start: "13:35:00",
    end: "15:20:00",
  },
  {
    oldId: 28,
    oldDayId: 10,
    label: "Afternoon B",
    order: 6,
    start: "15:20:00",
    end: "16:30:00",
  },
  {
    oldId: 29,
    oldDayId: 10,
    label: "Post-Session",
    order: 10,
    start: "16:30:00",
    end: "18:30:00",
  },
  // Sunday (day 14)
  {
    oldId: 51,
    oldDayId: 14,
    label: "Pre-Session",
    order: 1,
    start: "05:30:00",
    end: "09:45:00",
  },
  {
    oldId: 52,
    oldDayId: 14,
    label: "Morning A",
    order: 2,
    start: "09:20:00",
    end: "11:00:00",
  },
  {
    oldId: 54,
    oldDayId: 14,
    label: "Morning B",
    order: 2,
    start: "11:00:00",
    end: "12:10:00",
  },
  {
    oldId: 53,
    oldDayId: 14,
    label: "Lunch",
    order: 3,
    start: "12:10:00",
    end: "13:35:00",
  },
  {
    oldId: 55,
    oldDayId: 14,
    label: "Afternoon A",
    order: 5,
    start: "13:35:00",
    end: "14:35:00",
  },
  {
    oldId: 57,
    oldDayId: 14,
    label: "Afternoon B",
    order: 6,
    start: "14:35:00",
    end: "15:45:00",
  },
  {
    oldId: 56,
    oldDayId: 14,
    label: "Post-Session",
    order: 10,
    start: "15:35:00",
    end: "18:30:00",
  },
  // Thursday Test (day 23)
  {
    oldId: 72,
    oldDayId: 23,
    label: "Pre-Session",
    order: 1,
    start: "05:30:00",
    end: "09:45:00",
  },
  {
    oldId: 75,
    oldDayId: 23,
    label: "Morning A",
    order: 2,
    start: "09:20:00",
    end: "11:00:00",
  },
  {
    oldId: 76,
    oldDayId: 23,
    label: "Morning B",
    order: 2,
    start: "11:00:00",
    end: "12:10:00",
  },
  {
    oldId: 73,
    oldDayId: 23,
    label: "Lunch",
    order: 3,
    start: "12:10:00",
    end: "13:35:00",
  },
  {
    oldId: 74,
    oldDayId: 23,
    label: "Afternoon A",
    order: 5,
    start: "13:35:00",
    end: "14:35:00",
  },
  {
    oldId: 78,
    oldDayId: 23,
    label: "Afternoon B",
    order: 6,
    start: "14:35:00",
    end: "15:45:00",
  },
  {
    oldId: 77,
    oldDayId: 23,
    label: "Post-Session",
    order: 10,
    start: "15:35:00",
    end: "18:30:00",
  },
];

// Shifts — oldSessId maps to session via SESSIONS array
const SHIFTS = [
  // Friday Pre-Session (sess 7)
  {
    oldId: 9,
    oldSessId: 7,
    oldEtId: 2,
    label: "Ingress",
    start: "05:30:00",
    end: "09:45:00",
    dept: "lots_and_garages",
    need: null,
    code: null,
  },
  {
    oldId: 10,
    oldSessId: 7,
    oldEtId: 5,
    label: "Meeting",
    start: "06:15:00",
    end: "06:45:00",
    dept: null,
    need: null,
    code: null,
  },
  {
    oldId: 11,
    oldSessId: 7,
    oldEtId: 4,
    label: "Morning",
    start: "06:30:00",
    end: "10:00:00",
    dept: "dropoff_pickup",
    need: null,
    code: null,
  },
  {
    oldId: 13,
    oldSessId: 7,
    oldEtId: 6,
    label: "Morning",
    start: "05:30:00",
    end: "06:30:00",
    dept: "signs",
    need: null,
    code: null,
  },
  // Friday Morning A (sess 1)
  {
    oldId: 12,
    oldSessId: 1,
    oldEtId: 3,
    label: "Shift A",
    start: "09:45:00",
    end: "10:55:00",
    dept: "security",
    need: null,
    code: null,
  },
  // Friday Morning B (sess 2)
  {
    oldId: 14,
    oldSessId: 2,
    oldEtId: 3,
    label: "Shift B",
    start: "10:55:00",
    end: "12:05:00",
    dept: "security",
    need: null,
    code: null,
  },
  {
    oldId: 15,
    oldSessId: 2,
    oldEtId: 3,
    label: "Shift C",
    start: "12:05:00",
    end: "13:15:00",
    dept: "security",
    need: null,
    code: null,
  },
  // Friday Lunch (sess 3)
  {
    oldId: 16,
    oldSessId: 3,
    oldEtId: 3,
    label: "Shift D",
    start: "13:15:00",
    end: "14:25:00",
    dept: "security",
    need: null,
    code: null,
  },
  // Friday Afternoon A (sess 5)
  {
    oldId: 17,
    oldSessId: 5,
    oldEtId: 3,
    label: "Shift E",
    start: "14:25:00",
    end: "15:35:00",
    dept: "security",
    need: null,
    code: null,
  },
  // Friday Afternoon B (sess 6)
  {
    oldId: 18,
    oldSessId: 6,
    oldEtId: 3,
    label: "Shift F",
    start: "15:35:00",
    end: "16:45:00",
    dept: "security",
    need: null,
    code: null,
  },
  // Friday Post-Session (sess 8)
  {
    oldId: 19,
    oldSessId: 8,
    oldEtId: 2,
    label: "Egress",
    start: "16:30:00",
    end: "18:30:00",
    dept: "lots_and_garages",
    need: null,
    code: null,
  },
  {
    oldId: 20,
    oldSessId: 8,
    oldEtId: 4,
    label: "Pickup",
    start: "16:30:00",
    end: "18:30:00",
    dept: "dropoff_pickup",
    need: null,
    code: null,
  },
  {
    oldId: 21,
    oldSessId: 8,
    oldEtId: 6,
    label: "Evening",
    start: "18:00:00",
    end: "18:30:00",
    dept: "signs",
    need: null,
    code: null,
  },
  // Saturday Pre-Session (sess 23)
  {
    oldId: 22,
    oldSessId: 23,
    oldEtId: 2,
    label: "Ingress",
    start: "05:30:00",
    end: "09:45:00",
    dept: "lots_and_garages",
    need: null,
    code: null,
  },
  {
    oldId: 23,
    oldSessId: 23,
    oldEtId: 6,
    label: "Morning",
    start: "05:30:00",
    end: "06:30:00",
    dept: "signs",
    need: null,
    code: null,
  },
  {
    oldId: 24,
    oldSessId: 23,
    oldEtId: 5,
    label: "Meeting",
    start: "06:15:00",
    end: "06:45:00",
    dept: null,
    need: null,
    code: null,
  },
  {
    oldId: 25,
    oldSessId: 23,
    oldEtId: 4,
    label: "Morning",
    start: "06:30:00",
    end: "10:00:00",
    dept: "dropoff_pickup",
    need: null,
    code: null,
  },
  // Saturday Morning A (sess 24)
  {
    oldId: 26,
    oldSessId: 24,
    oldEtId: 3,
    label: "Shift A",
    start: "09:45:00",
    end: "10:50:00",
    dept: "security",
    need: null,
    code: null,
  },
  // Saturday Morning B (sess 25)
  {
    oldId: 27,
    oldSessId: 25,
    oldEtId: 3,
    label: "Shift B",
    start: "10:50:00",
    end: "11:55:00",
    dept: "security",
    need: null,
    code: null,
  },
  {
    oldId: 28,
    oldSessId: 25,
    oldEtId: 3,
    label: "Shift C",
    start: "11:55:00",
    end: "13:00:00",
    dept: "security",
    need: null,
    code: null,
  },
  // Saturday Lunch (sess 26)
  {
    oldId: 29,
    oldSessId: 26,
    oldEtId: 3,
    label: "Shift D",
    start: "13:00:00",
    end: "14:10:00",
    dept: "security",
    need: null,
    code: null,
  },
  // Saturday Afternoon A (sess 27)
  {
    oldId: 30,
    oldSessId: 27,
    oldEtId: 3,
    label: "Shift E",
    start: "14:10:00",
    end: "15:20:00",
    dept: "security",
    need: null,
    code: null,
  },
  // Saturday Afternoon B (sess 28)
  {
    oldId: 31,
    oldSessId: 28,
    oldEtId: 3,
    label: "Shift F",
    start: "15:20:00",
    end: "16:30:00",
    dept: "security",
    need: null,
    code: null,
  },
  // Saturday Post-Session (sess 29)
  {
    oldId: 32,
    oldSessId: 29,
    oldEtId: 2,
    label: "Egress",
    start: "16:20:00",
    end: "18:30:00",
    dept: "lots_and_garages",
    need: null,
    code: null,
  },
  {
    oldId: 33,
    oldSessId: 29,
    oldEtId: 4,
    label: "Pickup",
    start: "16:20:00",
    end: "18:30:00",
    dept: "dropoff_pickup",
    need: null,
    code: null,
  },
  {
    oldId: 34,
    oldSessId: 29,
    oldEtId: 6,
    label: "Evening",
    start: "18:00:00",
    end: "18:30:00",
    dept: "signs",
    need: null,
    code: null,
  },
  // Sunday Pre-Session (sess 51)
  {
    oldId: 74,
    oldSessId: 51,
    oldEtId: 2,
    label: "Ingress",
    start: "05:30:00",
    end: "09:45:00",
    dept: "lots_and_garages",
    need: null,
    code: null,
  },
  {
    oldId: 75,
    oldSessId: 51,
    oldEtId: 6,
    label: "Morning",
    start: "05:30:00",
    end: "06:30:00",
    dept: "signs",
    need: null,
    code: null,
  },
  {
    oldId: 76,
    oldSessId: 51,
    oldEtId: 5,
    label: "Meeting",
    start: "06:15:00",
    end: "06:45:00",
    dept: null,
    need: null,
    code: null,
  },
  {
    oldId: 77,
    oldSessId: 51,
    oldEtId: 4,
    label: "Morning",
    start: "06:30:00",
    end: "10:00:00",
    dept: "dropoff_pickup",
    need: null,
    code: null,
  },
  // Sunday Morning A (sess 52)
  {
    oldId: 78,
    oldSessId: 52,
    oldEtId: 3,
    label: "Shift A",
    start: "09:45:00",
    end: "10:45:00",
    dept: "security",
    need: null,
    code: null,
  },
  // Sunday Morning B (sess 54)
  {
    oldId: 80,
    oldSessId: 54,
    oldEtId: 3,
    label: "Shift B",
    start: "10:45:00",
    end: "11:45:00",
    dept: "security",
    need: null,
    code: null,
  },
  {
    oldId: 81,
    oldSessId: 54,
    oldEtId: 3,
    label: "Shift C",
    start: "11:45:00",
    end: "12:45:00",
    dept: "security",
    need: null,
    code: null,
  },
  // Sunday Lunch (sess 53)
  {
    oldId: 82,
    oldSessId: 53,
    oldEtId: 3,
    label: "Shift D",
    start: "12:45:00",
    end: "13:45:00",
    dept: "security",
    need: null,
    code: null,
  },
  // Sunday Afternoon A (sess 55)
  {
    oldId: 79,
    oldSessId: 55,
    oldEtId: 3,
    label: "Shift E",
    start: "13:45:00",
    end: "14:45:00",
    dept: "security",
    need: null,
    code: null,
  },
  // Sunday Afternoon B (sess 57)
  {
    oldId: 86,
    oldSessId: 57,
    oldEtId: 3,
    label: "Shift F",
    start: "14:45:00",
    end: "15:45:00",
    dept: "security",
    need: null,
    code: null,
  },
  // Sunday Post-Session (sess 56)
  {
    oldId: 83,
    oldSessId: 56,
    oldEtId: 2,
    label: "Egress",
    start: "16:20:00",
    end: "18:20:00",
    dept: "lots_and_garages",
    need: null,
    code: null,
  },
  {
    oldId: 84,
    oldSessId: 56,
    oldEtId: 6,
    label: "Evening",
    start: "18:00:00",
    end: "18:30:00",
    dept: "signs",
    need: null,
    code: null,
  },
  {
    oldId: 85,
    oldSessId: 56,
    oldEtId: 4,
    label: "Pickup",
    start: "16:20:00",
    end: "18:30:00",
    dept: "dropoff_pickup",
    need: null,
    code: null,
  },
  // Thursday Test Pre-Session (sess 72)
  {
    oldId: 109,
    oldSessId: 72,
    oldEtId: 2,
    label: "Ingress",
    start: "05:30:00",
    end: "09:45:00",
    dept: null,
    need: null,
    code: null,
  },
  {
    oldId: 110,
    oldSessId: 72,
    oldEtId: 6,
    label: "Morning",
    start: "05:30:00",
    end: "06:30:00",
    dept: null,
    need: null,
    code: null,
  },
  {
    oldId: 111,
    oldSessId: 72,
    oldEtId: 5,
    label: "Meeting",
    start: "06:15:00",
    end: "06:45:00",
    dept: null,
    need: null,
    code: null,
  },
  {
    oldId: 113,
    oldSessId: 72,
    oldEtId: 4,
    label: "Morning",
    start: "06:30:00",
    end: "10:00:00",
    dept: null,
    need: null,
    code: null,
  },
  // Thursday Test Morning A (sess 75)
  {
    oldId: 115,
    oldSessId: 75,
    oldEtId: 3,
    label: "Shift A",
    start: "09:45:00",
    end: "10:45:00",
    dept: null,
    need: null,
    code: null,
  },
  // Thursday Test Morning B (sess 76)
  {
    oldId: 116,
    oldSessId: 76,
    oldEtId: 3,
    label: "Shift B",
    start: "10:45:00",
    end: "11:45:00",
    dept: null,
    need: null,
    code: null,
  },
  {
    oldId: 117,
    oldSessId: 76,
    oldEtId: 3,
    label: "Shift C",
    start: "11:45:00",
    end: "12:45:00",
    dept: null,
    need: null,
    code: null,
  },
  // Thursday Test Lunch (sess 73)
  {
    oldId: 112,
    oldSessId: 73,
    oldEtId: 3,
    label: "Shift D",
    start: "12:45:00",
    end: "13:45:00",
    dept: null,
    need: null,
    code: null,
  },
  // Thursday Test Afternoon A (sess 74)
  {
    oldId: 114,
    oldSessId: 74,
    oldEtId: 3,
    label: "Shift E",
    start: "13:45:00",
    end: "14:45:00",
    dept: null,
    need: null,
    code: null,
  },
  // Thursday Test Afternoon B (sess 78)
  {
    oldId: 121,
    oldSessId: 78,
    oldEtId: 3,
    label: "Shift F",
    start: "14:45:00",
    end: "15:45:00",
    dept: null,
    need: null,
    code: null,
  },
  {
    oldId: 122,
    oldSessId: 78,
    oldEtId: 2,
    label: "Testing",
    start: "15:15:00",
    end: "17:00:00",
    dept: "lots_and_garages",
    need: null,
    code: "SPIN",
  },
  // Thursday Test Post-Session (sess 77)
  {
    oldId: 118,
    oldSessId: 77,
    oldEtId: 2,
    label: "Egress",
    start: "16:20:00",
    end: "18:20:00",
    dept: null,
    need: null,
    code: null,
  },
  {
    oldId: 119,
    oldSessId: 77,
    oldEtId: 4,
    label: "Pickup",
    start: "16:20:00",
    end: "18:30:00",
    dept: null,
    need: null,
    code: null,
  },
  {
    oldId: 120,
    oldSessId: 77,
    oldEtId: 6,
    label: "Evening",
    start: "18:00:00",
    end: "18:30:00",
    dept: null,
    need: null,
    code: null,
  },
];

// Assignments: [oldShiftId, oldLocationId, volunteerNeed, volMin, volMax]
const ASSIGNMENTS = [
  [9, 2, 20, 15, 25],
  [9, 1, 15, 0, 15],
  [11, 6, 4, 0, 4],
  [11, 5, 6, 0, 6],
  [12, 2, 2, 0, 2],
  [12, 1, 4, 0, 4],
  [14, 2, 2, 0, 2],
  [14, 1, 4, 0, 4],
  [15, 1, 4, 0, 4],
  [15, 2, 2, 0, 2],
  [16, 2, 2, 0, 2],
  [16, 1, 4, 0, 4],
  [17, 2, 2, 0, 2],
  [17, 1, 4, 0, 4],
  [18, 2, 2, 0, 2],
  [18, 1, 4, 0, 4],
  [19, 2, 15, 0, 15],
  [19, 1, 15, 0, 15],
  [20, 5, 6, 0, 6],
  [20, 6, 4, 0, 4],
  [22, 2, 15, 0, 15],
  [22, 1, 15, 0, 15],
  [25, 6, 4, 0, 4],
  [25, 5, 6, 0, 6],
  [26, 2, 2, 0, 2],
  [26, 1, 4, 0, 4],
  [27, 2, 2, 0, 2],
  [27, 1, 4, 0, 4],
  [28, 2, 2, 0, 2],
  [28, 1, 4, 0, 4],
  [29, 2, 2, 0, 2],
  [29, 1, 4, 0, 4],
  [30, 2, 2, 0, 2],
  [30, 1, 4, 0, 4],
  [31, 2, 2, 0, 2],
  [31, 1, 4, 0, 4],
  [32, 2, 15, 0, 15],
  [32, 1, 15, 0, 15],
  [33, 6, 4, 0, 4],
  [33, 5, 6, 0, 6],
  [74, 2, 15, 0, 15],
  [74, 1, 15, 0, 15],
  [77, 5, 6, 0, 6],
  [77, 6, 4, 0, 4],
  [78, 2, 2, 0, 2],
  [78, 1, 4, 0, 4],
  [79, 2, 2, 0, 2],
  [79, 1, 4, 0, 4],
  [80, 2, 2, 0, 2],
  [80, 1, 4, 0, 4],
  [81, 2, 2, 0, 2],
  [81, 1, 4, 0, 4],
  [82, 2, 2, 0, 2],
  [82, 1, 4, 0, 4],
  [83, 2, 15, 0, 15],
  [83, 1, 15, 0, 15],
  [85, 6, 4, 0, 4],
  [85, 5, 6, 0, 6],
  [86, 2, 2, 0, 2],
  [86, 1, 4, 0, 4],
  [109, 2, 15, null, 15],
  [109, 1, 15, null, 15],
  [112, 2, 2, null, 2],
  [112, 1, 4, null, 4],
  [113, 5, 6, null, 6],
  [113, 6, 4, null, 4],
  [114, 2, 2, null, 2],
  [114, 1, 4, null, 4],
  [115, 2, 2, null, 2],
  [115, 1, 4, null, 4],
  [116, 2, 2, null, 2],
  [116, 1, 4, null, 4],
  [117, 2, 2, null, 2],
  [117, 1, 4, null, 4],
  [118, 2, 15, null, 15],
  [118, 1, 15, null, 15],
  [119, 5, 6, null, 6],
  [119, 6, 4, null, 4],
  [121, 1, 4, null, 4],
  [121, 2, 2, null, 2],
  [122, 2, 4, 2, 4],
];

// Oversight structure: [oldVolId, oldParentVolId (or null for root), title, order]
// oldParentVolId refers to the volunteer's old dbo ID for the parent node
const HIERARCHY = [
  { oldVolId: 80, parentOldVolId: null, title: "Parking Overseer", order: 0 },
  {
    oldVolId: 84,
    parentOldVolId: 80,
    title: "Lots and Garages Overseer",
    order: 0,
  },
  {
    oldVolId: 81,
    parentOldVolId: 80,
    title: "Dropoff/Pickup Overseer",
    order: 1,
  },
  {
    oldVolId: null,
    parentOldVolId: 80,
    title: "Signs and Security Overseer",
    order: 2,
  },
  {
    oldVolId: 202,
    parentOldVolId: 80,
    title: "Assistant to Oversight, General",
    order: 3,
  },
];

// Real volunteer roster from dbo — emails anonymized, all data preserved
const VOLUNTEERS = [
  {
    oldId: 232,
    firstName: "Brian",
    lastName: "Alling",
    suffix: null,
    gender: "male",
    dob: "1974-07-06",
    stamina: 3,
    role: null,
    accountType: "non-registered",
    congregation: "Millbrook, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 1,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 0,
    smsAlerts: 0,
    lotsGarages: 1,
    signs: 1,
    security: 1,
    mobile: 1,
    dropoff: 1,
  },
  {
    oldId: 137,
    firstName: "Winston",
    lastName: "Austin",
    suffix: null,
    gender: "male",
    dob: "1998-08-26",
    stamina: 3,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Westport, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 1,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 1,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 1,
    signs: 1,
    security: 1,
    mobile: 0,
    dropoff: 1,
  },
  {
    oldId: 83,
    firstName: "Collin",
    lastName: "Begnoche",
    suffix: null,
    gender: "male",
    dob: "1998-02-08",
    stamina: 5,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "North - Clarksburg, NY",
    assignedToConv: 1,
    attendExtra: 1,
    elder: 0,
    regPioneer: 1,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 1,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 1,
    signs: null,
    security: 1,
    mobile: null,
    dropoff: null,
  },
  {
    oldId: 112,
    firstName: "Jeremy",
    lastName: "Boshart",
    suffix: null,
    gender: "male",
    dob: "1969-02-13",
    stamina: 5,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "South - Linwood, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 1,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 1,
    signs: null,
    security: 1,
    mobile: null,
    dropoff: null,
  },
  {
    oldId: 199,
    firstName: "Jeff",
    lastName: "Brownell",
    suffix: null,
    gender: "male",
    dob: "1965-05-01",
    stamina: 4,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Elmsdale, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 0,
    signs: 0,
    security: 1,
    mobile: 0,
    dropoff: 0,
  },
  {
    oldId: 168,
    firstName: "Sean",
    lastName: "Chrysler",
    suffix: null,
    gender: "male",
    dob: "1976-08-14",
    stamina: 4,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Kingsford, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 1,
    sfs: 0,
    smsOptIn: 0,
    smsAlerts: 0,
    lotsGarages: 0,
    signs: 0,
    security: 1,
    mobile: 0,
    dropoff: 0,
  },
  {
    oldId: 117,
    firstName: "Justin",
    lastName: "Cook",
    suffix: null,
    gender: "male",
    dob: "1982-05-13",
    stamina: 4,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "English - Harborview, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 1,
    specPioneer: 0,
    minServ: 1,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 1,
    signs: null,
    security: 1,
    mobile: null,
    dropoff: null,
  },
  {
    oldId: 84,
    firstName: "John",
    lastName: "Crankshaw",
    suffix: null,
    gender: "male",
    dob: "1973-08-02",
    stamina: 4,
    role: "OVERSEER",
    accountType: "registered",
    congregation: "Elmsdale, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 1,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: null,
    signs: null,
    security: 0,
    mobile: null,
    dropoff: null,
  },
  {
    oldId: 134,
    firstName: "Lucas",
    lastName: "Cunningham",
    suffix: null,
    gender: "male",
    dob: "1985-04-24",
    stamina: 4,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "North Weston, MA",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 1,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 1,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 1,
    signs: null,
    security: 1,
    mobile: null,
    dropoff: null,
  },
  {
    oldId: 89,
    firstName: "Rick",
    lastName: "Davis",
    suffix: null,
    gender: "male",
    dob: "1969-03-14",
    stamina: 4,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Kingsford, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 1,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 0,
    smsAlerts: 0,
    lotsGarages: 1,
    signs: null,
    security: 1,
    mobile: null,
    dropoff: null,
  },
  {
    oldId: 115,
    firstName: "Logan",
    lastName: "Detrick",
    suffix: null,
    gender: "male",
    dob: "2002-10-16",
    stamina: 5,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "South Northridge Falls, NY",
    assignedToConv: 1,
    attendExtra: 1,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 1,
    signs: null,
    security: 1,
    mobile: null,
    dropoff: null,
  },
  {
    oldId: 114,
    firstName: "Lee",
    lastName: "Duprey",
    suffix: null,
    gender: "male",
    dob: "1957-05-15",
    stamina: 4,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Ridgewood Valley, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 1,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 1,
    signs: null,
    security: 1,
    mobile: null,
    dropoff: null,
  },
  {
    oldId: 119,
    firstName: "Moses",
    lastName: "Duprey",
    suffix: null,
    gender: "male",
    dob: "1988-06-29",
    stamina: 4,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Harborfield, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 1,
    signs: null,
    security: 1,
    mobile: null,
    dropoff: null,
  },
  {
    oldId: 121,
    firstName: "Collin",
    lastName: "Erhardt",
    suffix: null,
    gender: "male",
    dob: "2005-06-26",
    stamina: 5,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Clearfield, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 1,
    signs: null,
    security: 1,
    mobile: null,
    dropoff: null,
  },
  {
    oldId: 214,
    firstName: "Osvaldo",
    lastName: "Estrada",
    suffix: null,
    gender: "male",
    dob: "1976-09-02",
    stamina: 2,
    role: "REGISTERED",
    accountType: "non-registered",
    congregation: "Kingsford, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 1,
    sfs: 0,
    smsOptIn: 0,
    smsAlerts: 0,
    lotsGarages: 1,
    signs: 0,
    security: 1,
    mobile: 0,
    dropoff: 0,
  },
  {
    oldId: 178,
    firstName: "Noah",
    lastName: "Ewbank",
    suffix: null,
    gender: "male",
    dob: "2004-12-27",
    stamina: 5,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Elmsdale, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 1,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 1,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 1,
    signs: null,
    security: 1,
    mobile: null,
    dropoff: null,
  },
  {
    oldId: 211,
    firstName: "Jeff",
    lastName: "Fagan",
    suffix: null,
    gender: "male",
    dob: "1982-07-30",
    stamina: 4,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Elmsdale, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 1,
    signs: 0,
    security: 1,
    mobile: 0,
    dropoff: 0,
  },
  {
    oldId: 81,
    firstName: "Ryan",
    lastName: "Fagan",
    suffix: null,
    gender: "male",
    dob: "1974-02-01",
    stamina: 5,
    role: "OVERSEER",
    accountType: "registered",
    congregation: "Elmsdale, NY",
    assignedToConv: 1,
    attendExtra: 1,
    elder: 1,
    regPioneer: 1,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: null,
    signs: null,
    security: 0,
    mobile: null,
    dropoff: null,
  },
  {
    oldId: 233,
    firstName: "Stephen",
    lastName: "Finch",
    suffix: null,
    gender: "male",
    dob: "1967-06-23",
    stamina: 2,
    role: null,
    accountType: "non-registered",
    congregation: "Kingsford, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 0,
    smsAlerts: 0,
    lotsGarages: 0,
    signs: 0,
    security: 0,
    mobile: 0,
    dropoff: 0,
  },
  {
    oldId: 241,
    firstName: "Zachary",
    lastName: "Folts",
    suffix: null,
    gender: "male",
    dob: "1988-10-25",
    stamina: 5,
    role: null,
    accountType: "registered",
    congregation: "Ravenswood, NY",
    assignedToConv: 1,
    attendExtra: 1,
    elder: 1,
    regPioneer: 1,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 0,
    smsAlerts: 0,
    lotsGarages: 0,
    signs: 0,
    security: 0,
    mobile: 0,
    dropoff: 0,
  },
  {
    oldId: 176,
    firstName: "Vahe",
    lastName: "Garabedian",
    suffix: null,
    gender: "male",
    dob: "1962-01-01",
    stamina: 4,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Harborfield, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 1,
    regPioneer: 1,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 1,
    signs: null,
    security: 1,
    mobile: null,
    dropoff: null,
  },
  {
    oldId: 122,
    firstName: "Elijah",
    lastName: "Garcia",
    suffix: null,
    gender: "male",
    dob: "2005-11-19",
    stamina: 4,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Ridgecrest, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 1,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 1,
    signs: null,
    security: 1,
    mobile: null,
    dropoff: null,
  },
  {
    oldId: 206,
    firstName: "Tom",
    lastName: "Gifford",
    suffix: null,
    gender: "male",
    dob: "1961-04-29",
    stamina: 3,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Elmsdale, NY",
    assignedToConv: 1,
    attendExtra: 1,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 1,
    signs: 0,
    security: 1,
    mobile: 0,
    dropoff: 0,
  },
  {
    oldId: 193,
    firstName: "Jayson",
    lastName: "Glover",
    suffix: null,
    gender: "male",
    dob: "1981-01-08",
    stamina: 2,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "South - Lakeview, NY",
    assignedToConv: 1,
    attendExtra: 1,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 1,
    signs: 0,
    security: 1,
    mobile: 0,
    dropoff: 0,
  },
  {
    oldId: 215,
    firstName: "Bobby",
    lastName: "Guaschino",
    suffix: null,
    gender: "male",
    dob: "1984-02-27",
    stamina: 4,
    role: "REGISTERED",
    accountType: "non-registered",
    congregation: "Cedarfield, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 1,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 0,
    smsAlerts: 0,
    lotsGarages: 1,
    signs: 0,
    security: 1,
    mobile: 0,
    dropoff: 0,
  },
  {
    oldId: 230,
    firstName: "Shane",
    lastName: "Gulotta",
    suffix: null,
    gender: "male",
    dob: "1973-05-09",
    stamina: 5,
    role: "REGISTERED",
    accountType: "non-registered",
    congregation: "Elmsdale, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 1,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 1,
    smsOptIn: 0,
    smsAlerts: 0,
    lotsGarages: 0,
    signs: 0,
    security: 0,
    mobile: 0,
    dropoff: 0,
  },
  {
    oldId: 167,
    firstName: "Daniel",
    lastName: "Hart",
    suffix: null,
    gender: "male",
    dob: "1985-10-16",
    stamina: 5,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Kingsford, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 1,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 0,
    signs: 1,
    security: 1,
    mobile: 1,
    dropoff: null,
  },
  {
    oldId: 238,
    firstName: "Matthew",
    lastName: "Hebert",
    suffix: null,
    gender: "male",
    dob: "2006-04-05",
    stamina: 4,
    role: null,
    accountType: "non-registered",
    congregation: "Harborfield, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 1,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 0,
    smsAlerts: 0,
    lotsGarages: 0,
    signs: 0,
    security: 0,
    mobile: 0,
    dropoff: 0,
  },
  {
    oldId: 82,
    firstName: "Scott",
    lastName: "Holmes",
    suffix: null,
    gender: "male",
    dob: "1995-06-10",
    stamina: 5,
    role: "OVERSEER",
    accountType: "registered",
    congregation: "Harborfield, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 1,
    regPioneer: 1,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: null,
    signs: null,
    security: 0,
    mobile: null,
    dropoff: null,
  },
  {
    oldId: 131,
    firstName: "Rohit",
    lastName: "Kanchan",
    suffix: null,
    gender: "male",
    dob: "1990-01-01",
    stamina: 4,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Millhaven, NY",
    assignedToConv: 1,
    attendExtra: 1,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 1,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 1,
    signs: null,
    security: 1,
    mobile: null,
    dropoff: null,
  },
  {
    oldId: 231,
    firstName: "Rockiem",
    lastName: "Kennedy",
    suffix: null,
    gender: "male",
    dob: "1986-10-29",
    stamina: 2,
    role: null,
    accountType: "registered",
    congregation: "South - Riverdale, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 0,
    smsAlerts: 0,
    lotsGarages: 0,
    signs: 0,
    security: 0,
    mobile: 0,
    dropoff: 0,
  },
  {
    oldId: 138,
    firstName: "Shane",
    lastName: "King",
    suffix: null,
    gender: "male",
    dob: "1992-12-08",
    stamina: 3,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Elmsdale, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 1,
    signs: null,
    security: 1,
    mobile: null,
    dropoff: null,
  },
  {
    oldId: 208,
    firstName: "Matthew",
    lastName: "Kirk",
    suffix: null,
    gender: "male",
    dob: "1996-07-07",
    stamina: 5,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Elmsdale, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 1,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 1,
    signs: 0,
    security: 1,
    mobile: 0,
    dropoff: 0,
  },
  {
    oldId: 198,
    firstName: "Nicholas",
    lastName: "Kirk",
    suffix: null,
    gender: "male",
    dob: "1984-05-22",
    stamina: 5,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Elmsdale, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 0,
    signs: 0,
    security: 1,
    mobile: 0,
    dropoff: 0,
  },
  {
    oldId: 88,
    firstName: "Matthew",
    lastName: "Kyarsgaard",
    suffix: null,
    gender: "male",
    dob: "1968-04-11",
    stamina: 3,
    role: "KEYMAN",
    accountType: "non-registered",
    congregation: "Northridge Falls, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 1,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: null,
    signs: null,
    security: 1,
    mobile: null,
    dropoff: null,
  },
  {
    oldId: 80,
    firstName: "Jacob",
    lastName: "Ladd",
    suffix: null,
    gender: "male",
    dob: "1983-09-19",
    stamina: 5,
    role: "ADMIN",
    accountType: "registered",
    congregation: "Millhaven, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 1,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 1,
    lotsGarages: 1,
    signs: 1,
    security: 1,
    mobile: 1,
    dropoff: 1,
  },
  {
    oldId: 237,
    firstName: "Jason",
    lastName: "Ladd",
    suffix: null,
    gender: "male",
    dob: "1983-09-19",
    stamina: 5,
    role: "DESK",
    accountType: "registered",
    congregation: "English - Harborview, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 1,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 0,
    smsAlerts: 0,
    lotsGarages: 0,
    signs: 0,
    security: 0,
    mobile: 0,
    dropoff: 0,
  },
  {
    oldId: 203,
    firstName: "Earl",
    lastName: "Lamphear",
    suffix: null,
    gender: "male",
    dob: "1983-06-04",
    stamina: 4,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Elmsdale, NY",
    assignedToConv: 1,
    attendExtra: 1,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 0,
    signs: 1,
    security: 1,
    mobile: 0,
    dropoff: 0,
  },
  {
    oldId: 227,
    firstName: "Jude",
    lastName: "Leight",
    suffix: null,
    gender: "male",
    dob: "2006-11-12",
    stamina: 5,
    role: "REGISTERED",
    accountType: "non-registered",
    congregation: "Cedarfield, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 0,
    signs: 0,
    security: 0,
    mobile: 0,
    dropoff: 0,
  },
  {
    oldId: 133,
    firstName: "Cody",
    lastName: "Lowry",
    suffix: null,
    gender: "male",
    dob: "1992-12-21",
    stamina: 4,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Elmsdale, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 0,
    smsAlerts: 0,
    lotsGarages: null,
    signs: 1,
    security: 1,
    mobile: null,
    dropoff: null,
  },
  {
    oldId: 132,
    firstName: "Mirko",
    lastName: "Manrique",
    suffix: null,
    gender: "male",
    dob: "2003-05-27",
    stamina: 4,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Elmsdale, NY",
    assignedToConv: 1,
    attendExtra: 1,
    elder: 0,
    regPioneer: 1,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 1,
    sfs: 0,
    smsOptIn: 0,
    smsAlerts: 0,
    lotsGarages: null,
    signs: 1,
    security: 1,
    mobile: null,
    dropoff: null,
  },
  {
    oldId: 116,
    firstName: "Mirko",
    lastName: "Manrique Fong",
    suffix: null,
    gender: "male",
    dob: "1969-10-05",
    stamina: 5,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Elmsdale, NY",
    assignedToConv: 1,
    attendExtra: 1,
    elder: 0,
    regPioneer: 1,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 1,
    sfs: 0,
    smsOptIn: 0,
    smsAlerts: 0,
    lotsGarages: null,
    signs: 1,
    security: 1,
    mobile: null,
    dropoff: null,
  },
  {
    oldId: 192,
    firstName: "Cameron",
    lastName: "McKee",
    suffix: null,
    gender: "male",
    dob: "1994-03-01",
    stamina: 5,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "South Northridge Falls, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 0,
    signs: 1,
    security: 1,
    mobile: 0,
    dropoff: 0,
  },
  {
    oldId: 207,
    firstName: "Thomas",
    lastName: "Mogensen",
    suffix: null,
    gender: "male",
    dob: "1999-03-13",
    stamina: 4,
    role: "REGISTERED",
    accountType: "non-registered",
    congregation: "Elmsdale, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 1,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 0,
    signs: 0,
    security: 1,
    mobile: 0,
    dropoff: 1,
  },
  {
    oldId: 195,
    firstName: "Danny",
    lastName: "Munoz",
    suffix: null,
    gender: "male",
    dob: "1978-01-08",
    stamina: 4,
    role: "ASSISTANT_ADMIN",
    accountType: "registered",
    congregation: "Millhaven, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 1,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 0,
    signs: 0,
    security: 0,
    mobile: 0,
    dropoff: 0,
  },
  {
    oldId: 163,
    firstName: "Amos",
    lastName: "Page",
    suffix: "Jr",
    gender: "male",
    dob: "1966-06-03",
    stamina: 4,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Kingsford, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 1,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: null,
    signs: null,
    security: 1,
    mobile: null,
    dropoff: 1,
  },
  {
    oldId: 169,
    firstName: "Bryce",
    lastName: "Parker",
    suffix: null,
    gender: "male",
    dob: "2000-06-13",
    stamina: 4,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Cedarfield, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: null,
    signs: null,
    security: 1,
    mobile: null,
    dropoff: 1,
  },
  {
    oldId: 197,
    firstName: "Reese",
    lastName: "Parker",
    suffix: null,
    gender: "male",
    dob: "2002-07-13",
    stamina: 4,
    role: "NON_REGISTERED",
    accountType: "registered",
    congregation: "Cedarfield, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 0,
    signs: 0,
    security: 1,
    mobile: 0,
    dropoff: 0,
  },
  {
    oldId: 213,
    firstName: "Paul",
    lastName: "Patulski",
    suffix: null,
    gender: "male",
    dob: "1950-01-07",
    stamina: 3,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Elmsdale, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 1,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 0,
    signs: 0,
    security: 1,
    mobile: 0,
    dropoff: 1,
  },
  {
    oldId: 194,
    firstName: "Joseph",
    lastName: "Potter",
    suffix: null,
    gender: "male",
    dob: "1968-01-14",
    stamina: 2,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Clearfield, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 0,
    signs: 0,
    security: 1,
    mobile: 0,
    dropoff: 1,
  },
  {
    oldId: 234,
    firstName: "Alec",
    lastName: "Raynor",
    suffix: null,
    gender: "male",
    dob: "1998-10-23",
    stamina: 3,
    role: null,
    accountType: "non-registered",
    congregation: "South - Lakeview, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 0,
    signs: 0,
    security: 0,
    mobile: 0,
    dropoff: 0,
  },
  {
    oldId: 140,
    firstName: "Nevin",
    lastName: "Raynor",
    suffix: null,
    gender: "male",
    dob: "1996-01-08",
    stamina: 3,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "South - Lakeview, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: null,
    signs: null,
    security: 1,
    mobile: 1,
    dropoff: 1,
  },
  {
    oldId: 210,
    firstName: "Anthony",
    lastName: "Rebecca",
    suffix: null,
    gender: "male",
    dob: "1990-04-13",
    stamina: 5,
    role: "ASSISTANT_ADMIN",
    accountType: "registered",
    congregation: "Kingsford, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 1,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 0,
    smsAlerts: 0,
    lotsGarages: 0,
    signs: 0,
    security: 0,
    mobile: 0,
    dropoff: 0,
  },
  {
    oldId: 142,
    firstName: "Josiah",
    lastName: "Rivera",
    suffix: null,
    gender: "male",
    dob: "2006-04-11",
    stamina: 3,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Kingsford, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 1,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: null,
    signs: null,
    security: 1,
    mobile: 1,
    dropoff: 1,
  },
  {
    oldId: 240,
    firstName: "Aaron",
    lastName: "Saul",
    suffix: null,
    gender: "male",
    dob: "2008-09-07",
    stamina: 4,
    role: "DESK",
    accountType: "registered",
    congregation: "Millhaven, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 1,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 0,
    smsAlerts: 0,
    lotsGarages: 0,
    signs: 0,
    security: 0,
    mobile: 0,
    dropoff: 0,
  },
  {
    oldId: 236,
    firstName: "Micah",
    lastName: "Saul",
    suffix: null,
    gender: "male",
    dob: "2011-04-20",
    stamina: 3,
    role: "DESK",
    accountType: "registered",
    congregation: "Millhaven, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 1,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 0,
    smsAlerts: 0,
    lotsGarages: 0,
    signs: 0,
    security: 0,
    mobile: 0,
    dropoff: 0,
  },
  {
    oldId: 85,
    firstName: "Brian",
    lastName: "Schiemer",
    suffix: null,
    gender: "male",
    dob: "1972-01-27",
    stamina: 4,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Elmsdale, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 1,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: null,
    signs: null,
    security: 1,
    mobile: 1,
    dropoff: null,
  },
  {
    oldId: 173,
    firstName: "Brian",
    lastName: "Smith",
    suffix: null,
    gender: "male",
    dob: "1960-09-27",
    stamina: 4,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Ironwood, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 1,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: null,
    signs: null,
    security: 1,
    mobile: 1,
    dropoff: null,
  },
  {
    oldId: 202,
    firstName: "Liam",
    lastName: "Smith",
    suffix: null,
    gender: "male",
    dob: "2000-01-05",
    stamina: 4,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Elmsdale, NY",
    assignedToConv: 1,
    attendExtra: 1,
    elder: 1,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 0,
    signs: 0,
    security: 1,
    mobile: 0,
    dropoff: 0,
  },
  {
    oldId: 216,
    firstName: "Ryan",
    lastName: "Thomas",
    suffix: null,
    gender: "male",
    dob: "1978-01-20",
    stamina: 5,
    role: "ASSISTANT_ADMIN",
    accountType: "registered",
    congregation: "Ashgrove, NY",
    assignedToConv: 1,
    attendExtra: 1,
    elder: 1,
    regPioneer: 1,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 0,
    smsAlerts: 0,
    lotsGarages: 0,
    signs: 0,
    security: 0,
    mobile: 0,
    dropoff: 0,
  },
  {
    oldId: 175,
    firstName: "John",
    lastName: "Tomchik",
    suffix: null,
    gender: "male",
    dob: "1957-05-01",
    stamina: 4,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Kingsford, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 1,
    sfs: 0,
    smsOptIn: 0,
    smsAlerts: 0,
    lotsGarages: null,
    signs: null,
    security: 1,
    mobile: null,
    dropoff: null,
  },
  {
    oldId: 165,
    firstName: "Aubrey",
    lastName: "Welch",
    suffix: null,
    gender: "male",
    dob: "1995-07-11",
    stamina: 4,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Ferndale, VT",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 1,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: null,
    signs: null,
    security: 1,
    mobile: null,
    dropoff: null,
  },
  {
    oldId: 144,
    firstName: "Caleb",
    lastName: "Wells",
    suffix: null,
    gender: "male",
    dob: "1994-07-23",
    stamina: 5,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "North - Lakeview, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 1,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: null,
    signs: null,
    security: 1,
    mobile: null,
    dropoff: null,
  },
  {
    oldId: 120,
    firstName: "Aidan",
    lastName: "Wilkes",
    suffix: null,
    gender: "male",
    dob: "2003-09-16",
    stamina: 4,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Cedarfield, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 1,
    specPioneer: 0,
    minServ: 1,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: null,
    signs: null,
    security: 1,
    mobile: null,
    dropoff: null,
  },
  {
    oldId: 196,
    firstName: "Brennan",
    lastName: "Wilkes",
    suffix: null,
    gender: "male",
    dob: "2001-07-20",
    stamina: 5,
    role: "NON_REGISTERED",
    accountType: "registered",
    congregation: "Cedarfield, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 0,
    signs: 0,
    security: 1,
    mobile: 0,
    dropoff: 0,
  },
  {
    oldId: 242,
    firstName: "Benjamin",
    lastName: "Williams",
    suffix: null,
    gender: "male",
    dob: "2010-04-27",
    stamina: 5,
    role: "DESK",
    accountType: "registered",
    congregation: "Millhaven, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 0,
    smsAlerts: 0,
    lotsGarages: 0,
    signs: 0,
    security: 0,
    mobile: 0,
    dropoff: 0,
  },
  {
    oldId: 118,
    firstName: "Maurice",
    lastName: "Williams",
    suffix: null,
    gender: "male",
    dob: "1998-06-09",
    stamina: 5,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "South - Riverdale, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 0,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: null,
    signs: null,
    security: 1,
    mobile: null,
    dropoff: null,
  },
  {
    oldId: 164,
    firstName: "Jay",
    lastName: "Wynn",
    suffix: null,
    gender: "male",
    dob: "1975-07-09",
    stamina: 4,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Kingsford, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 1,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: null,
    signs: null,
    security: 1,
    mobile: null,
    dropoff: null,
  },
  {
    oldId: 177,
    firstName: "Travis",
    lastName: "Wynn",
    suffix: null,
    gender: "male",
    dob: "1982-01-14",
    stamina: 3,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Kingsford, NY",
    assignedToConv: 1,
    attendExtra: 0,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 1,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: null,
    signs: null,
    security: 1,
    mobile: null,
    dropoff: null,
  },
  {
    oldId: 190,
    firstName: "Brisbane",
    lastName: "Young",
    suffix: null,
    gender: "male",
    dob: "1966-04-26",
    stamina: 4,
    role: "REGISTERED",
    accountType: "registered",
    congregation: "Northridge Falls, NY",
    assignedToConv: 1,
    attendExtra: 1,
    elder: 0,
    regPioneer: 0,
    auxPioneer: 0,
    specPioneer: 0,
    minServ: 1,
    sfs: 0,
    smsOptIn: 1,
    smsAlerts: 0,
    lotsGarages: 1,
    signs: 0,
    security: 1,
    mobile: 0,
    dropoff: 0,
  },
];

// Unique congregations extracted from volunteer data
const CONGREGATIONS = [
  { congregation: "Millbrook", state: "NY" },
  { congregation: "Ridgewood Valley", state: "NY" },
  { congregation: "Cedarfield", state: "NY" },
  { congregation: "Ravenswood", state: "NY" },
  { congregation: "Westport", state: "NY" },
  { congregation: "English - Harborview", state: "NY" },
  { congregation: "Clearfield", state: "NY" },
  { congregation: "Northridge Falls", state: "NY" },
  { congregation: "Elmsdale", state: "NY" },
  { congregation: "Kingsford", state: "NY" },
  { congregation: "Ashgrove", state: "NY" },
  { congregation: "Ridgecrest", state: "NY" },
  { congregation: "Ferndale", state: "VT" },
  { congregation: "North - Clarksburg", state: "NY" },
  { congregation: "North - Lakeview", state: "NY" },
  { congregation: "North Weston", state: "MA" },
  { congregation: "Harborfield", state: "NY" },
  { congregation: "Millhaven", state: "NY" },
  { congregation: "Stonegate", state: "NY" },
  { congregation: "South - Riverdale", state: "NY" },
  { congregation: "South - Linwood", state: "NY" },
  { congregation: "South - Lakeview", state: "NY" },
  { congregation: "South Northridge Falls", state: "NY" },
  { congregation: "Ironwood", state: "NY" },
];

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
async function seed() {
  log("Connecting as", DEMO_USER, "...");
  const pool = await new sql.ConnectionPool(poolConfig).connect();
  log("Connected. Beginning seed...");

  try {
    // -------------------------------------------------------------------
    // 0. Clear all tables (FK-safe order)
    // -------------------------------------------------------------------
    log("Clearing demo tables...");
    const clears = [
      "shift_alert_log",
      "shift_alert_schedules",
      "shift_slot_assignments",
      "schedule_publishes",
      "schedule_assignments",
      "invitation_revocation_log",
      "invitations",
      "invitation_batches",
      "shifts",
      "sessions",
      "volunteer_blackouts",
      "oversightstructure",
      "sms_opt_out_log",
      "attendance",
      "bug_reports",
      "message_templates",
      "role_permissions",
      "convention_days",
      "event_types",
      "locations_tasks",
      "volunteer_in",
      "roles",
      "congregations",
    ];
    for (const t of clears) await pool.request().query(`DELETE FROM ${t};`);
    log("Tables cleared.");

    // -------------------------------------------------------------------
    // 1. Congregations
    // -------------------------------------------------------------------
    log("Seeding congregations...");
    for (const c of CONGREGATIONS) {
      await pool
        .request()
        .input("name", sql.NVarChar(150), c.congregation)
        .input("state", sql.NVarChar(100), c.state)
        .query(
          `INSERT INTO congregations (congregation, State) VALUES (@name, @state);`,
        );
    }
    log(`  ${CONGREGATIONS.length} congregations.`);

    // -------------------------------------------------------------------
    // 2. Roles
    // -------------------------------------------------------------------
    log("Seeding roles...");
    const roleRows = [
      {
        name: "NON_REGISTERED",
        level: 0,
        desc: "Can submit registration info only",
      },
      { name: "REGISTERED", level: 1, desc: "Can view schedules and maps" },
      {
        name: "KEYMAN",
        level: 2,
        desc: "Can view and print assignments and maps",
      },
      {
        name: "DESK",
        level: 2,
        desc: "Can create volunteer accounts and log attendance",
      },
      {
        name: "OVERSEER",
        level: 3,
        desc: "Can create and manage assignments and shifts",
      },
      {
        name: "ASSISTANT_ADMIN",
        level: 4,
        desc: "All privileges except managing admin accounts",
      },
      { name: "ADMIN", level: 5, desc: "Full sitewide access" },
    ];
    for (const r of roleRows) {
      await pool
        .request()
        .input("name", sql.NVarChar(50), r.name)
        .input("level", sql.Int, r.level)
        .input("desc", sql.NVarChar(500), r.desc)
        .query(
          `INSERT INTO roles (role_name, oversightstructure_level, description) VALUES (@name, @level, @desc);`,
        );
    }
    log(`  ${roleRows.length} roles.`);

    // -------------------------------------------------------------------
    // 3. Event types — build oldId → newId map
    // -------------------------------------------------------------------
    log("Seeding event types...");
    const etMap = {}; // oldId → newId
    for (const et of EVENT_TYPES) {
      const r = await pool
        .request()
        .input("name", sql.NVarChar(100), et.name)
        .input("desc", sql.NVarChar(500), et.description)
        .input("color", sql.NVarChar(7), et.color)
        .input("by", sql.NVarChar(100), "admin@demo.com")
        .query(
          `INSERT INTO event_types (name, description, color, created_by) OUTPUT INSERTED.id VALUES (@name, @desc, @color, @by);`,
        );
      etMap[et.oldId] = r.recordset[0].id;
    }
    log(`  ${EVENT_TYPES.length} event types. Map:`, etMap);

    // -------------------------------------------------------------------
    // 4. Locations — build oldId → newId map
    // -------------------------------------------------------------------
    log("Seeding locations & tasks...");
    const locMap = {}; // oldId → newId
    for (const loc of LOCATIONS) {
      const r = await pool
        .request()
        .input("year", sql.Int, YEAR)
        .input("name", sql.NVarChar(100), loc.name)
        .input("type", sql.NVarChar(20), loc.type)
        .input("desc", sql.NVarChar(500), loc.description)
        .input("cap", sql.Int, loc.capacity)
        .input("address", sql.NVarChar(255), loc.address)
        .input("lat", sql.Decimal(9, 6), loc.lat)
        .input("lng", sql.Decimal(9, 6), loc.lng)
        .input("mapsUrl", sql.NVarChar(500), loc.maps_url)
        .input("by", sql.NVarChar(100), "admin@demo.com")
        .query(
          `INSERT INTO locations_tasks (year, name, type, description, capacity, address, lat, lng, maps_url, created_by) OUTPUT INSERTED.id VALUES (@year, @name, @type, @desc, @cap, @address, @lat, @lng, @mapsUrl, @by);`,
        );
      locMap[loc.oldId] = r.recordset[0].id;
    }
    log(`  ${LOCATIONS.length} locations/tasks. Map:`, locMap);

    // -------------------------------------------------------------------
    // 5. Convention days — build oldId → newId map
    // -------------------------------------------------------------------
    log("Seeding convention days...");
    const dayMap = {}; // oldId → newId
    for (const d of CONVENTION_DAYS) {
      const r = await pool
        .request()
        .input("year", sql.Int, YEAR)
        .input("label", sql.NVarChar(50), d.label)
        .input("date", sql.Date, new Date(d.date + "T12:00:00Z"))
        .input("start", sql.NVarChar(8), d.start)
        .input("end", sql.NVarChar(8), d.end)
        .input("sched", sql.Bit, d.schedulable)
        .query(
          `INSERT INTO convention_days (year, label, convention_date, program_start, program_end, schedulable) OUTPUT INSERTED.id VALUES (@year, @label, @date, @start, @end, @sched);`,
        );
      dayMap[d.oldId] = r.recordset[0].id;
    }
    log(`  ${CONVENTION_DAYS.length} convention days. Map:`, dayMap);

    // -------------------------------------------------------------------
    // 6. Sessions — build oldId → newId map
    // -------------------------------------------------------------------
    log("Seeding sessions...");
    const sessMap = {}; // oldId → newId
    for (const s of SESSIONS) {
      const newDayId = dayMap[s.oldDayId];
      if (!newDayId) {
        log(
          `  WARN: no day mapping for session oldId=${s.oldId} oldDayId=${s.oldDayId}`,
        );
        continue;
      }
      const r = await pool
        .request()
        .input("dayId", sql.Int, newDayId)
        .input("label", sql.NVarChar(50), s.label)
        .input("order", sql.Int, s.order)
        .input("start", sql.NVarChar(8), s.start)
        .input("end", sql.NVarChar(8), s.end)
        .query(
          `INSERT INTO sessions (convention_day_id, label, session_order, start_time, end_time) OUTPUT INSERTED.id VALUES (@dayId, @label, @order, @start, @end);`,
        );
      sessMap[s.oldId] = r.recordset[0].id;
    }
    log(`  ${Object.keys(sessMap).length} sessions.`);

    // -------------------------------------------------------------------
    // 7. Shifts — build oldId → newId map
    // -------------------------------------------------------------------
    log("Seeding shifts...");
    const shiftMap = {}; // oldId → newId
    for (const sh of SHIFTS) {
      const newSessId = sessMap[sh.oldSessId];
      const newEtId = etMap[sh.oldEtId];
      if (!newSessId) {
        log(
          `  WARN: no session mapping for shift oldId=${sh.oldId} oldSessId=${sh.oldSessId}`,
        );
        continue;
      }
      if (!newEtId) {
        log(
          `  WARN: no event_type mapping for shift oldId=${sh.oldId} oldEtId=${sh.oldEtId}`,
        );
        continue;
      }
      const r = await pool
        .request()
        .input("sessId", sql.Int, newSessId)
        .input("etId", sql.Int, newEtId)
        .input("label", sql.NVarChar(50), sh.label)
        .input("start", sql.NVarChar(8), sh.start)
        .input("end", sql.NVarChar(8), sh.end)
        .input("dept", sql.NVarChar(50), sh.dept)
        .input("need", sql.Int, sh.need)
        .input("code", sql.NVarChar(8), sh.code)
        .query(
          `INSERT INTO shifts (session_id, event_type_id, label, start_time, end_time, department, volunteer_need, sms_code) OUTPUT INSERTED.id VALUES (@sessId, @etId, @label, @start, @end, @dept, @need, @code);`,
        );
      shiftMap[sh.oldId] = r.recordset[0].id;
    }
    log(`  ${Object.keys(shiftMap).length} shifts.`);

    // -------------------------------------------------------------------
    // 8. Schedule assignments
    // -------------------------------------------------------------------
    log("Seeding schedule assignments...");
    let assignCount = 0;
    for (const [oldShiftId, oldLocId, need, volMin, volMax] of ASSIGNMENTS) {
      const newShiftId = shiftMap[oldShiftId];
      const newLocId = locMap[oldLocId];
      if (!newShiftId) {
        log(`  WARN: no shift mapping for assignment shiftId=${oldShiftId}`);
        continue;
      }
      if (!newLocId) {
        log(`  WARN: no loc mapping for assignment locId=${oldLocId}`);
        continue;
      }
      await pool
        .request()
        .input("shiftId", sql.Int, newShiftId)
        .input("locId", sql.Int, newLocId)
        .input("need", sql.Int, need)
        .input("volMin", sql.Int, volMin)
        .input("volMax", sql.Int, volMax)
        .query(
          `INSERT INTO schedule_assignments (shift_id, location_task_id, volunteer_need, vol_min, vol_max) VALUES (@shiftId, @locId, @need, @volMin, @volMax);`,
        );
      assignCount++;
    }
    log(`  ${assignCount} assignments.`);

    // -------------------------------------------------------------------
    // 9. Volunteers — real roster, anonymized emails
    // -------------------------------------------------------------------
    log("Seeding volunteers...");
    const oldIdToNewId = {}; // old dbo id → new demo id
    for (const v of VOLUNTEERS) {
      const email =
        NAMED_EMAIL_MAP[v.oldId] ??
        `${v.firstName.toLowerCase().replace(/\s+/g, "-")}.${v.lastName.toLowerCase().replace(/\s+/g, "-")}.${v.oldId}@demo.com`;

      const isNamed = !!NAMED_EMAIL_MAP[v.oldId];
      const pwPayload = isNamed ? hashPassword(DEMO_PASS_PW) : null;

      const req = pool.request();
      req.input("email", sql.NVarChar(255), email);
      req.input("firstName", sql.NVarChar(100), v.firstName);
      req.input("lastName", sql.NVarChar(100), v.lastName);
      req.input("suffix", sql.NVarChar(20), v.suffix);
      req.input("gender", sql.NVarChar(20), v.gender);
      req.input("dobirth", sql.Date, new Date(v.dob + "T12:00:00Z"));
      req.input("stamina", sql.Int, v.stamina);
      req.input("role", sql.NVarChar(20), v.role);
      req.input("accountType", sql.NVarChar(50), v.accountType);
      req.input("congregation", sql.NVarChar(255), v.congregation);
      req.input("assignedToConv", sql.Bit, v.assignedToConv);
      req.input("attendExtra", sql.Bit, v.attendExtra);
      req.input("elder", sql.Bit, v.elder);
      req.input("regPioneer", sql.Bit, v.regPioneer);
      req.input("auxPioneer", sql.Bit, v.auxPioneer);
      req.input("specPioneer", sql.Bit, v.specPioneer);
      req.input("minServ", sql.Bit, v.minServ);
      req.input("sfs", sql.Bit, v.sfs);
      req.input("smsOptIn", sql.Bit, v.smsOptIn);
      req.input("smsAlerts", sql.Bit, v.smsAlerts);
      req.input("lotsGarages", sql.Bit, v.lotsGarages);
      req.input("signs", sql.Bit, v.signs);
      req.input("security", sql.Bit, v.security);
      req.input("mobile", sql.Bit, v.mobile);
      req.input("dropoff", sql.Bit, v.dropoff);
      req.input("pwHash", sql.VarBinary(32), pwPayload?.hash ?? null);
      req.input("pwSalt", sql.VarBinary(16), pwPayload?.salt ?? null);
      req.input("pwIter", sql.Int, pwPayload?.iterations ?? null);
      req.input("pwAlgo", sql.NVarChar(50), pwPayload?.algo ?? null);

      const result = await req.query(`
                INSERT INTO volunteer_in (
                    email, firstName, lastName, suffix, gender, dobirth, stamina,
                    role, accountType, congregation, assignedToConv, attendExtra,
                    elder, regPioneer, auxPioneer, specPioneer, minServ, sfs,
                    sms_opted_in, sms_shift_alerts_opt_in,
                    crew_lots_garages, crew_signs, crew_security,
                    crew_mobile_support, crew_dropoff_pickup,
                    passwordHash, passwordSalt, passwordIter, passwordAlgo,
                    registration_status, account_status, active_current_year
                )
                OUTPUT INSERTED.id
                VALUES (
                    @email, @firstName, @lastName, @suffix, @gender, @dobirth, @stamina,
                    @role, @accountType, @congregation, @assignedToConv, @attendExtra,
                    @elder, @regPioneer, @auxPioneer, @specPioneer, @minServ, @sfs,
                    @smsOptIn, @smsAlerts,
                    @lotsGarages, @signs, @security, @mobile, @dropoff,
                    @pwHash, @pwSalt, @pwIter, @pwAlgo,
                    'completed', 'ok', 1
                );
            `);
      oldIdToNewId[v.oldId] = result.recordset[0].id;
    }
    log(`  ${VOLUNTEERS.length} volunteers. Named accounts mapped.`);

    // -------------------------------------------------------------------
    // 10. Oversight structure
    // -------------------------------------------------------------------
    log("Seeding oversight structure...");
    // Insert root first, then children. Build nodeVolId → nodeId map.
    const oversightstructureNodeMap = {}; // oldVolId → new oversight structurenode id (for parent lookup)
    for (const h of HIERARCHY) {
      const newVolId =
        h.oldVolId != null ? (oldIdToNewId[h.oldVolId] ?? null) : null;
      const newParentId =
        h.parentOldVolId != null
          ? (oversightstructureNodeMap[h.parentOldVolId] ?? null)
          : null;
      const r = await pool
        .request()
        .input("volId", sql.Int, newVolId)
        .input("parentId", sql.Int, newParentId)
        .input("title", sql.NVarChar(100), h.title)
        .input("order", sql.Int, h.order)
        .query(
          `INSERT INTO oversight structure(volunteer_id, parent_id, role_title, sort_order) OUTPUT INSERTED.id VALUES (@volId, @parentId, @title, @order);`,
        );
      if (h.oldVolId != null) oversightstructureNodeMap[h.oldVolId] = r.recordset[0].id;
      else oversightstructureNodeMap[`null_${h.order}`] = r.recordset[0].id; // null-vol node
    }
    log("  Oversight structure (5 nodes) seeded.");

    // -------------------------------------------------------------------
    // 11. Message templates
    // -------------------------------------------------------------------
    log("Seeding message templates...");
    const templates = [
      {
        name: "Standard Invitation",
        subject: "You're Invited — 2026 Riverdale JW Regional Convention Parking",
        body: "Dear [Name],\n\nWe'd like to invite you to serve on the parking team for the 2026 Riverdale JW Regional Convention. Please respond using the link below.\n\nThank you!",
      },
      {
        name: "Reminder — No Response",
        subject: "Friendly Reminder — Convention Parking Invitation",
        body: "Dear [Name],\n\nThis is a friendly reminder that we haven't yet received your response. Please respond at your earliest convenience.",
      },
      {
        name: "Shift Alert",
        subject: "Your Parking Shift is Coming Up",
        body: "Dear [Name],\n\nThis is a reminder that you're scheduled for a parking shift: [Shift Details].\n\nPlease arrive 15 minutes early. Reply CHECK to confirm arrival.\n\nThank you!",
      },
    ];
    for (const t of templates) {
      await pool
        .request()
        .input("name", sql.NVarChar(100), t.name)
        .input("subject", sql.NVarChar(255), t.subject)
        .input("body", sql.NVarChar(sql.MAX), t.body)
        .input("by", sql.NVarChar(100), "admin@demo.com")
        .query(
          `INSERT INTO message_templates (name, subject, body, created_by) VALUES (@name, @subject, @body, @by);`,
        );
    }
    log(`  ${templates.length} message templates.`);

    // -------------------------------------------------------------------
    // 12. Sample invitation batch (Friday)
    // -------------------------------------------------------------------
    log("Seeding invitation batch...");
    const fridayNewId = dayMap[1]; // old day 1 = Friday
    const batchR = await pool
      .request()
      .input(
        "name",
        sql.NVarChar(150),
        "2026 Initial Invitation — All Volunteers",
      )
      .input("dayId", sql.Int, fridayNewId)
      .input(
        "subj",
        sql.NVarChar(255),
        "You're Invited — 2026 Riverdale JW Regional Convention Parking",
      )
      .input(
        "body",
        sql.NVarChar(sql.MAX),
        "Dear [Name], we would like to invite you to serve on the parking team this year.",
      )
      .input("year", sql.Int, YEAR)
      .input("by", sql.NVarChar(100), "admin@demo.com")
      .input("resp", sql.Bit, 1)
      .input("type", sql.NVarChar(20), "invitation")
      .query(
        `INSERT INTO invitation_batches (name, convention_day_id, message_subject, message_body, year, created_by, response_needed, message_type) OUTPUT INSERTED.id VALUES (@name, @dayId, @subj, @body, @year, @by, @resp, @type);`,
      );
    const batchId = batchR.recordset[0].id;

    // Send to first 8 volunteers — vary responses
    const responses = ["yes", "yes", "yes", "yes", null, null, null, null];
    const invVols = VOLUNTEERS.slice(0, 8);
    let invCount = 0;
    for (const v of invVols) {
      const newVolId = oldIdToNewId[v.oldId];
      const responded = responses[invCount] ? new Date() : null;
      await pool
        .request()
        .input("volId", sql.Int, newVolId)
        .input("token", sql.NVarChar(100), crypto.randomUUID())
        .input("channel", sql.NVarChar(10), "email")
        .input(
          "subj",
          sql.NVarChar(255),
          "You're Invited — 2026 Riverdale JW Regional Convention Parking",
        )
        .input("body", sql.NVarChar(sql.MAX), "Invitation text.")
        .input("sentBy", sql.NVarChar(100), "admin@demo.com")
        .input("dayId", sql.Int, fridayNewId)
        .input("batchId", sql.Int, batchId)
        .input("responded", sql.DateTime2, responded)
        .input("response", sql.NVarChar(10), responses[invCount])
        .query(
          `INSERT INTO invitations (volunteer_id, token, channel, message_subject, message_body, sent_by, convention_day_id, batch_id, responded_at, response) VALUES (@volId, @token, @channel, @subj, @body, @sentBy, @dayId, @batchId, @responded, @response);`,
        );
      invCount++;
    }
    log(`  Batch ${batchId} with ${invCount} invitations (4 yes, 4 pending).`);

    // -------------------------------------------------------------------
    // Done
    // -------------------------------------------------------------------
    log("");
    log("=========================================");
    log("  Demo seed complete!");
    log("  Volunteers: " + VOLUNTEERS.length);
    log("  Convention days: " + CONVENTION_DAYS.length + " (3 schedulable)");
    log("  Sessions: " + Object.keys(sessMap).length);
    log("  Shifts: " + Object.keys(shiftMap).length);
    log("  Assignments: " + assignCount);
    log("=========================================");
    log("");
    log("Login credentials (password: Demo@2026!):");
    log("  admin@demo.com        ADMIN           (Jacob Ladd)");
    log("  asstadmin@demo.com    ASSISTANT_ADMIN (Danny Munoz)");
    log("  overseer@demo.com     OVERSEER        (Ryan Fagan)");
    log("  keyman@demo.com       KEYMAN          (Matthew Kyarsgaard)");
    log("  desk@demo.com         DESK            (Jason Ladd)");
    log("  volunteer@demo.com    REGISTERED      (Winston Austin)");
  } finally {
    await pool.close();
    log("Connection closed.");
  }
}

seed().catch((err) => {
  logError("Seed failed:", err);
  process.exit(1);
});
